lab3Crud/Models/Department.cs
namespace lab3Crud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Department")]
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            Instructors = new HashSet<Instructor>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Dept_Id { get; set; }

        [StringLength(50)]
        public string Dept_Name { get; set; }

        [StringLength(100)]
        public string Dept_Desc { get; set; }

        [StringLength(50)]
        public string Dept_Location { get; set; }

        public int? Dept_Manager { get; set; }

        [Column(TypeName = "date")]
        public DateTime? Manager_hiredate { get; set; }

        public virtual Instructor Instructor { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructor> Instructors { get; set; }
    }
}

lab3Crud/Models/ITI.cs
namespace lab3Crud.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class ITI : DbContext
    {
        public ITI()
            : base("name=ITI")
        {
        }

        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Department>()
                .HasMany(e => e.Instructors)
                .WithOptional(e => e.Department)
                .HasForeignKey(e => e.Dept_Id);

            modelBuilder.Entity<Instructor>()
                .Property(e => e.Salary)
                .HasPrecision(19, 4);

            modelBuilder.Entity<Instructor>()
                .HasMany(e => e.Departments)
                .WithOptional(e => e.Instructor)
                .HasForeignKey(e => e.Dept_Manager);
        }
    }
}

lab3Crud/Models/Instructor.cs
namespace lab3Crud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Instructor")]
    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            Departments = new HashSet<Department>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Ins_Id { get; set; }

        [StringLength(50)]
        public string Ins_Name { get; set; }

        [StringLength(50)]
        public string Ins_Degree { get; set; }

        [Column(TypeName = "money")]
        public decimal? Salary { get; set; }

        public int? Dept_Id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }

        public virtual Department Department { get; set; }
    }
}

lab3Crud/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab3Crud.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

lab3Crud/Controllers/lab3Controller.cs
using lab3Crud.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lab3Crud.Controllers
{
    public class lab3Controller : Controller
    {
        // GET: lab3
        ITI db = new ITI(); 
        public ActionResult Index()
        {
            List<Instructor> ins = db.Instructors.ToList();
            return View(ins);
        }
        public ActionResult details(int id)
        {
            Instructor s = db.Instructors.Where(n => n.Ins_Id == id).FirstOrDefault();
            return View(s);
        }

        public ActionResult edit(int id)
        {
            
            List<Department> dp = db.Departments.ToList();
            SelectList li = new SelectList(dp, "Dept_Id","Dept_Name");
            ViewBag.li = li;
            Instructor ss = db.Instructors.Where(s => s.Ins_Id == id).FirstOrDefault();
            return View(ss);
        }
        [HttpPost]
        public ActionResult edit(Instructor ins)
        {
            db.Entry(ins).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        
        
        public ActionResult create()
        {
            List<Department> dp = db.Departments.ToList();
            SelectList li = new SelectList(dp, "Dept_Id", "Dept_Name");
            ViewBag.li = li;

            return View();
        }
        [HttpPost]
        public ActionResult create(Instructor ins)
        {
            db.Instructors.Add(ins);
            db.SaveChanges();

            List<Instructor> sts = db.Instructors.Include(n => n.Department).ToList();
            return View("Index", sts);

        }

        public ActionResult delete(int id)
        {
            Instructor s = db.Instructors.Where(n => n.Ins_Id == id).FirstOrDefault();

            db.Instructors.Remove(s);
            db.SaveChanges();


            return RedirectToAction("index");
        }

    }

}

lab3Crud/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

lab3Crud/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

lab3Crud/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

lab3Crud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

lab3Crud/Views/lab3/Index.cshtml
@model List<lab3Crud.Models.Instructor>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @Html.ActionLink("new Instructor","create")
        <table border="1" style="width:100%; text-align:center;">
            <tr><th>id</th> <th>name</th><th>department</th><th></th></tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Ins_Id</td>
                    <td>@item.Ins_Name</td>
                    <td>@item.Department.Dept_Name</td>

                    <td>
                        @Html.ActionLink("view", "details", "lab3", new { id = item.Ins_Id }, new { })
                        |
                        @Html.ActionLink("Edit", "edit", "lab3", new { id = item.Ins_Id }, new { })

                        |
                        @Html.ActionLink("delete", "delete", "lab3", new { id = item.Ins_Id }, new { onClick = "return confirm('are you sure to delete this student?')" })


                    </td>
                </tr>
            }


        </table>
    </div>
</body>
</html>

lab3Crud/Views/lab3/create.cshtml
@model lab3Crud.Models.Instructor
@{
    ViewBag.Title = "create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>create</title>
</head>
<body>
    <div>
        <form method="post">
            
            <table>
                <tr>
                    <td>@Html.LabelFor(n => n.Ins_Id)</td>
                    <td>@Html.TextBoxFor(n => n.Ins_Id)</td>
                    <td>@Html.ValidationMessageFor(n => n.Ins_Id)</td>
                </tr>

                <tr>
                    <td>@Html.LabelFor(n => n.Ins_Name)</td>
                    <td>@Html.TextBoxFor(n => n.Ins_Name)</td>
                    <td>@Html.ValidationMessageFor(n => n.Ins_Name)</td>
                </tr>


                <tr>
                    <td>@Html.LabelFor(n => n.Dept_Id)</td>
                    <td>@Html.DropDownListFor(n => n.Dept_Id, (SelectList)ViewBag.li)</td>
                    <td>@Html.ValidationMessageFor(n => n.Dept_Id)</td>
                </tr>

            </table>


            <input type="submit" value="save" />

            <script src="~/Scripts/jquery-1.10.2.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>
            <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

        </form>
    </div>
</body>
</html>

lab3Crud/Views/lab3/details.cshtml
@model lab3Crud.Models.Instructor
@{
    ViewBag.Title = "details";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>details</title>
</head>
<body>
    <div>
        <table border="1" style="text-align:center; width:500px;">
            <tr>
                <th> id</th>
                <td>@Model.Dept_Id</td>
            </tr>
            <tr>
                <th> name</th>
                <td>@Model.Ins_Name</td>
            </tr>


            <tr>
                <th> department name</th>
                <td>@Model.Department.Dept_Name</td>
            </tr>

        </table>
    </div>
</body>
</html>

lab3Crud/Views/lab3/edit.cshtml
@model lab3Crud.Models.Instructor
@{
    ViewBag.Title = "edit";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>edit</title>
</head>
<body>
    <div>
        <form method="post">
            @Html.HiddenFor(x=>x.Ins_Id)
            <table>


                <tr>
                    <td>@Html.LabelFor(n => n.Ins_Name)</td>
                    <td>@Html.TextBoxFor(n => n.Ins_Name)</td>
                    <td>@Html.ValidationMessageFor(n => n.Ins_Name)</td>
                </tr>
                @*<tr>
                    <td>@Html.LabelFor(n => n.Ins_Id)</td>
                    <td>@Html.TextBoxFor(n => n.Ins_Id)</td>
                    <td>@Html.ValidationMessageFor(n => n.Ins_Id)</td>
                </tr>*@
               
                <tr>
                    <td>@Html.LabelFor(n => n.Dept_Id)</td>
                    <td>@Html.DropDownListFor(n => n.Dept_Id, (SelectList)ViewBag.li)</td>
                    <td>@Html.ValidationMessageFor(n => n.Dept_Id)</td>
                </tr>

            </table>


            <input type="submit" value="save" />

            <script src="~/Scripts/jquery-1.10.2.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>
            <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

        </form>
    </div>
</body>
</html>